def create_solver_file(best_solution):
    with open("minesweeper_solver.py", "w") as file:
        file.write("from minesweeper import Minesweeper\n")
        file.write("import config\n")
        file.write("import tkinter as tk\n")
        file.write("from tkinter import messagebox\n\n")

        file.write("class MinesweeperGUI:\n")
        file.write("    def __init__(self, master, game, moves):\n")
        file.write("        self.master = master\n")
        file.write("        self.game = game\n")
        file.write("        self.moves = moves\n")
        file.write("        self.buttons = [[tk.Button(master, width=2, height=1) for _ in range(game.size)] for _ in range(game.size)]\n")
        file.write("        for y in range(game.size):\n")
        file.write("            for x in range(game.size):\n")
        file.write("                btn = self.buttons[y][x]\n")
        file.write("                btn.grid(row=y, column=x)\n")
        file.write("        self.next_move()\n\n")
        
        file.write("    def next_move(self):\n")
        file.write("        if not self.moves:\n")
        file.write("            messagebox.showinfo('Fim', 'Todos os movimentos foram realizados!')\n")
        file.write("            return\n")
        file.write("        move = self.moves.pop(0)\n")
        file.write("        success = self.game.open_cell(*move)\n")
        file.write("        self.update_buttons()\n")
        file.write("        self.master.after(500, self.next_move)\n\n")
        
        file.write("    def update_buttons(self):\n")
        file.write("        for y in range(self.game.size):\n")
        file.write("            for x in range(self.game.size):\n")
        file.write("                btn = self.buttons[y][x]\n")
        file.write("                if self.game.opened[y][x]:\n")
        file.write("                    btn.config(text=str(self.game.board[y][x]))\n\n")

        file.write("def solve():\n")
        file.write("    root = tk.Tk()\n")
        file.write("    game = Minesweeper(config.BOARD_SIZE, config.NUM_MINES)\n")
        file.write("    moves = " + str(best_solution.genome) + "\n")
        file.write("    gui = MinesweeperGUI(root, game, moves)\n")
        file.write("    root.mainloop()\n\n")

        file.write("if __name__ == '__main__':\n")
        file.write("    solve()\n")
